### ISSUE TITLE
라이센스 문의

### ISSUE THREAD

**Issue by 20160553** [kimjaebeom98/Sign-Language-Translator#2]
개인 프로젝트에 비상업적 용도로 사용해보려 하는데, 사용이 가능할까요?

**Comment by kimjaebeom98** [comment]
> 개인 프로젝트에 비상업적 용도로 사용해보려 하는데, 사용이 가능할까요?

네네 가능합니다 해보시고 필요하신 파일들 있으시면 메일로 연락주시면 드리겠습니다.

**Comment by 20160553** [comment]
감사합니다.
